#[derive(Debug, Copy, Clone, PartialEq)]
pub enum SyntaxKind {
    Unknown,
    EndOfFileToken,
    // Literals
    NumericLiteral,
    StringLiteral,
    RegularExpressionLiteral,
    // Punctuation
    OpenBraceToken,
    CloseBraceToken,
    OpenParenToken,
    CloseParenToken,
    OpenBracketToken,
    CloseBracketToken,
    DotToken,
    DotDotDotToken,
    SemicolonToken,
    CommaToken,
    LessThanToken,
    GreaterThanToken,
    LessThanEqualsToken,
    GreaterThanEqualsToken,
    EqualsEqualsToken,
    ExclamationEqualsToken,
    EqualsEqualsEqualsToken,
    ExclamationEqualsEqualsToken,
    EqualsGreaterThanToken,
    PlusToken,
    MinusToken,
    AsteriskToken,
    SlashToken,
    PercentToken,
    PlusPlusToken,
    MinusMinusToken,
    LessThanLessThanToken,
    GreaterThanGreaterThanToken,
    GreaterThanGreaterThanGreaterThanToken,
    AmpersandToken,
    BarToken,
    CaretToken,
    ExclamationToken,
    TildeToken,
    AmpersandAmpersandToken,
    BarBarToken,
    QuestionToken,
    ColonToken,
    // Assignments
    EqualsToken,
    PlusEqualsToken,
    MinusEqualsToken,
    AsteriskEqualsToken,
    SlashEqualsToken,
    PercentEqualsToken,
    LessThanLessThanEqualsToken,
    GreaterThanGreaterThanEqualsToken,
    GreaterThanGreaterThanGreaterThanEqualsToken,
    AmpersandEqualsToken,
    BarEqualsToken,
    CaretEqualsToken,
    // Identifiers
    Identifier,
    // Reserved words
    BreakKeyword,
    CaseKeyword,
    CatchKeyword,
    ClassKeyword,
    ConstKeyword,
    ContinueKeyword,
    DebuggerKeyword,
    DefaultKeyword,
    DeleteKeyword,
    DoKeyword,
    ElseKeyword,
    EnumKeyword,
    ExportKeyword,
    ExtendsKeyword,
    FalseKeyword,
    FinallyKeyword,
    ForKeyword,
    FunctionKeyword,
    IfKeyword,
    ImportKeyword,
    InKeyword,
    InstanceOfKeyword,
    NewKeyword,
    NullKeyword,
    ReturnKeyword,
    SuperKeyword,
    SwitchKeyword,
    ThisKeyword,
    ThrowKeyword,
    TrueKeyword,
    TryKeyword,
    TypeOfKeyword,
    VarKeyword,
    VoidKeyword,
    WhileKeyword,
    WithKeyword,
    // Strict mode reserved words
    ImplementsKeyword,
    InterfaceKeyword,
    LetKeyword,
    PackageKeyword,
    PrivateKeyword,
    ProtectedKeyword,
    PublicKeyword,
    StaticKeyword,
    YieldKeyword,
    // TypeScript keywords
    AnyKeyword,
    BooleanKeyword,
    ConstructorKeyword,
    DeclareKeyword,
    GetKeyword,
    ModuleKeyword,
    RequireKeyword,
    NumberKeyword,
    SetKeyword,
    StringKeyword,
    // Parse tree nodes
    Missing,
    // Names
    QualifiedName,
    // Signature elements
    TypeParameter,
    Parameter,
    // TypeMember
    Property,
    Method,
    Constructor,
    GetAccessor,
    SetAccessor,
    CallSignature,
    ConstructSignature,
    IndexSignature,
    // Type
    TypeReference,
    TypeQuery,
    TypeLiteral,
    ArrayType,
    // Expression
    ArrayLiteral,
    ObjectLiteral,
    PropertyAssignment,
    PropertyAccess,
    IndexedAccess,
    CallExpression,
    NewExpression,
    TypeAssertion,
    ParenExpression,
    FunctionExpression,
    ArrowFunction,
    PrefixOperator,
    PostfixOperator,
    BinaryExpression,
    ConditionalExpression,
    OmittedExpression,
    // Element
    Block,
    VariableStatement,
    EmptyStatement,
    ExpressionStatement,
    IfStatement,
    DoStatement,
    WhileStatement,
    ForStatement,
    ForInStatement,
    ContinueStatement,
    BreakStatement,
    ReturnStatement,
    WithStatement,
    SwitchStatement,
    CaseClause,
    DefaultClause,
    LabelledStatement,
    ThrowStatement,
    TryStatement,
    TryBlock,
    CatchBlock,
    FinallyBlock,
    DebuggerStatement,
    VariableDeclaration,
    FunctionDeclaration,
    FunctionBlock,
    ClassDeclaration,
    InterfaceDeclaration,
    EnumDeclaration,
    ModuleDeclaration,
    ModuleBlock,
    ImportDeclaration,
    ExportAssignment,
    // Enum
    EnumMember,
    // Top-level nodes
    SourceFile,
    Program,
    // Synthesized list
    SyntaxList,
    // Enum value count
    Count,
}

// Markers
pub mod markers {
    use super::SyntaxKind;

    pub const FIRST_ASSIGNMENT: SyntaxKind = SyntaxKind::EqualsToken;
    pub const LAST_ASSIGNMENT: SyntaxKind = SyntaxKind::CaretEqualsToken;
    pub const FIRST_RESERVED_WORD: SyntaxKind = SyntaxKind::BreakKeyword;
    pub const LAST_RESERVED_WORD: SyntaxKind = SyntaxKind::WithKeyword;
    pub const FIRST_KEYWORD: SyntaxKind = SyntaxKind::BreakKeyword;
    pub const LAST_KEYWORD: SyntaxKind = SyntaxKind::StringKeyword;
    pub const FIRST_FUTURE_RESERVED_WORD: SyntaxKind = SyntaxKind::ImplementsKeyword;
    pub const LAST_FUTURE_RESERVED_WORD: SyntaxKind = SyntaxKind::YieldKeyword;
    pub const FIRST_TYPE_NODE: SyntaxKind = SyntaxKind::TypeReference;
    pub const LAST_TYPE_NODE: SyntaxKind = SyntaxKind::ArrayType;
    pub const FIRST_PUNCTUATION: SyntaxKind = SyntaxKind::OpenBraceToken;
    pub const LAST_PUNCTUATION: SyntaxKind = SyntaxKind::CaretEqualsToken;
}
